"""Constants for foxBMS POSIX vECU fault injection tests.

Contains CAN IDs, SIL override command bytes, BMS state definitions,
DIAG ID mappings, severity offsets, timeouts, and skip lists.
"""

# CAN IDs for SIL override and probe frames
CAN_OVERRIDE_ID = 0x7E0
CAN_PROBE_SPS = 0x7F0
CAN_PROBE_CELL_VOLTAGE = 0x7F4
CAN_PROBE_TEMPERATURE = 0x7F6
CAN_PROBE_DIAG = 0x7F7
CAN_PROBE_DIAG_BITMAP = 0x7F8
CAN_PROBE_STATE = 0x7F9
CAN_PROBE_CURRENT = 0x7FA
CAN_BMS_STATE_MSG = 0x220

# SIL override command bytes (from sil_layer.h)
SIL_CELL_VOLTAGE = 0x01
SIL_CELL_TEMP = 0x02
SIL_PACK_CURRENT = 0x03
SIL_SOC = 0x04
SIL_CONTACTOR_FB = 0x05
SIL_INTERLOCK = 0x06
SIL_PACK_VOLTAGE = 0x07
SIL_DIAG_FORCE = 0x08
SIL_DIAG_CLEAR = 0x09
SIL_CLEAR_ALL = 0xFF

# BMS states (from foxBMS state machine)
BMS_UNINITIALIZED = 0
BMS_INITIALIZATION = 1
BMS_INITIALIZED = 2
BMS_IDLE = 3
BMS_OPEN_CONTACTORS = 4
BMS_STANDBY = 5
BMS_PRECHARGE = 6
BMS_NORMAL = 7
BMS_DISCHARGE = 8
BMS_CHARGE = 9
BMS_ERROR = 10

BMS_STATE_NAMES = {
    0: "UNINITIALIZED", 1: "INITIALIZATION", 2: "INITIALIZED",
    3: "IDLE", 4: "OPEN_CONTACTORS", 5: "STANDBY",
    6: "PRECHARGE", 7: "NORMAL", 8: "DISCHARGE",
    9: "CHARGE", 10: "ERROR",
}

# Default timeouts
DEFAULT_TIMEOUT_MS = 5000
RECOVERY_TIMEOUT_S = 10.0
STARTUP_TIMEOUT_S = 30.0

# DIAG ID enum mapping (from foxBMS diag_cfg.h)
DIAG_ID_MAP = {
    "DIAG_ID_CELLVOLTAGE_OVERVOLTAGE": 18,
    "DIAG_ID_CELLVOLTAGE_UNDERVOLTAGE": 21,
    "DIAG_ID_TEMP_OVERTEMPERATURE_CHARGE": 24,
    "DIAG_ID_TEMP_OVERTEMPERATURE_DISCHARGE": 27,
    "DIAG_ID_TEMP_UNDERTEMPERATURE_CHARGE": 30,
    "DIAG_ID_TEMP_UNDERTEMPERATURE_DISCHARGE": 33,
    "DIAG_ID_OVERCURRENT_CHARGE_CELL": 36,
    "DIAG_ID_OVERCURRENT_DISCHARGE_CELL": 39,
    "DIAG_ID_STRING_OVERCURRENT_CHARGE": 42,
    "DIAG_ID_STRING_OVERCURRENT_DISCHARGE": 45,
    "DIAG_ID_OVERCURRENT_CHARGE_PACK": 48,
    "DIAG_ID_OVERCURRENT_DISCHARGE_PACK": 49,
    "DIAG_ID_PACKVOLTAGE": 50,
    "DIAG_ID_PLAUSIBILITY_CELLVOLTAGE": 51,
    "DIAG_ID_PLAUSIBILITY_CELLTEMPERATURE": 52,
}

# Severity tier to DIAG ID offset within group of 3 (MSL=0, RSL=1, MOL=2)
SEVERITY_OFFSET = {
    "OV_MSL": 0, "OV_RSL": 1, "OV_MOL": 2,
    "UV_MSL": 0, "UV_RSL": 1, "UV_MOL": 2,
    "OT_DIS_MSL": 0, "OT_DIS_RSL": 1, "OT_DIS_MOL": 2,
    "OT_CHG_MSL": 0, "OT_CHG_RSL": 1, "OT_CHG_MOL": 2,
    "UT_DIS_MSL": 0, "UT_DIS_RSL": 1, "UT_DIS_MOL": 2,
    "UT_CHG_MSL": 0, "UT_CHG_RSL": 1, "UT_CHG_MOL": 2,
    "OC_DISCHARGE_MSL": 0, "OC_DISCHARGE_RSL": 1, "OC_DISCHARGE_MOL": 2,
    "OC_CHARGE_MSL": 0, "OC_CHARGE_RSL": 1, "OC_CHARGE_MOL": 2,
}

# Fault methods that need special handling (skip for now)
SKIP_FAULT_METHODS = {"MISSING_TIMEOUT", "CAN_BUS_FAULT", "STUCK_AT_LAST"}

# BMS states we cannot currently set up
SKIP_BMS_STATES = {
    "IDLE", "STANDBY", "PRECHARGE", "ERROR",
    "UNINITIALIZED", "INITIALIZED", "SYS_CHECK",
    "CHARGE", "DISCHARGE", "OPEN_CONTACTORS",
}

# Expected reactions we cannot currently verify
SKIP_REACTIONS = {
    "BOOT_BLOCKED", "TRANSITION_OK", "REQUEST_REJECTED",
    "STATE_NORMAL", "CHECK_TIMING", "RATE_LIMITED",
    "SKIP_CROSS_FAULT",
}

# Target types we cannot inject
SKIP_TARGET_TYPES = {"special", "state_transition"}
